apiVersion: apps/v1
kind: Deployment
metadata:
  name: joseph-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joseph
  template:
    metadata:
      labels:
        app: joseph
    spec:
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
---
# Writing Service.yaml to expose the app
apiVersion: v1
kind: Service
metadata:
  name: joseph-app-svc
spec:
  selector:
    app: joseph
  ports:
  - port: 3016 # Service port
    targetPort: 3015 # Container port 
  type: LoadBalancer 
